// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bottleneck_distance
double bottleneck_distance(const Rcpp::NumericMatrix& x, const Rcpp::NumericMatrix& y, const double delta);
RcppExport SEXP _phutil_bottleneck_distance(SEXP xSEXP, SEXP ySEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(bottleneck_distance(x, y, delta));
    return rcpp_result_gen;
END_RCPP
}
// wasserstein_distance
double wasserstein_distance(const Rcpp::NumericMatrix& x, const Rcpp::NumericMatrix& y, const double wasserstein_power, const double delta);
RcppExport SEXP _phutil_wasserstein_distance(SEXP xSEXP, SEXP ySEXP, SEXP wasserstein_powerSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type wasserstein_power(wasserstein_powerSEXP);
    Rcpp::traits::input_parameter< const double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(wasserstein_distance(x, y, wasserstein_power, delta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_phutil_bottleneck_distance", (DL_FUNC) &_phutil_bottleneck_distance, 3},
    {"_phutil_wasserstein_distance", (DL_FUNC) &_phutil_wasserstein_distance, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_phutil(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
