# Generated by cpp11: do not edit by hand

bottleneckDistance <- function(x, y, delta) {
  .Call(`_phutil_bottleneckDistance`, x, y, delta)
}

wassersteinDistance <- function(x, y, delta, wasserstein_power) {
  .Call(`_phutil_wassersteinDistance`, x, y, delta, wasserstein_power)
}
