# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bottleneck distance between two persistence diagrams
#'
#' This function computes the Bottleneck distance between two persistence
#' diagrams of the same homology dimension. The diagrams must be represented as
#' 2-column matrices. The first column of the matrix contains the birth times
#' and the second column contains the death times of the points.
#'
#' @param x A matrix of shape \eqn{n \times 2} specifying the first persistence
#'   diagram.
#' @param y A matrix of shape \eqn{m \times 2} specifying the second
#'   persistence diagram.
#' @param delta A numeric value specifying the relative error. Defaults to
#'   `0.0` in which case the exact Bottleneck distance is computed. If `delta`
#'   is greater than `0.0`, an approximate Bottleneck distance is computed.
#'
#' @return A numeric value storing the Bottleneck distance between the two
#'   persistence diagrams.
#'
#' @examples
#' bottleneck_distance(
#'   persistence_sample[[1]]$pairs[[1]],
#'   persistence_sample[[2]]$pairs[[1]]
#' )
#'
#' @export
bottleneck_distance <- function(x, y, delta = 0.0) {
    .Call(`_phutil_bottleneck_distance`, x, y, delta)
}

#' Wasserstein distance between two persistence diagrams
#'
#' This function computes the Wasserstein distance between two persistence
#' diagrams of the same homology dimension. The diagrams must be represented as
#' 2-column matrices. The first column of the matrix contains the birth times
#' and the second column contains the death times of the points.
#'
#' @param x A matrix of shape \eqn{n \times 2} specifying the first persistence
#'   diagram.
#' @param y A matrix of shape \eqn{m \times 2} specifying the second
#'   persistence diagram.
#' @param wasserstein_power A numeric value specifying the power of the
#'   Wasserstein distance. Defaults to `1.0`.
#' @param delta A numeric value specifying the relative error. Defaults to
#'   `0.01`.
#'
#' @return A numeric value storing the Wasserstein distance between the two
#'   persistence diagrams.
#'
#' @examples
#' wasserstein_distance(
#'   persistence_sample[[1]]$pairs[[1]],
#'   persistence_sample[[2]]$pairs[[1]]
#' )
#'
#' @export
wasserstein_distance <- function(x, y, wasserstein_power = 1.0, delta = 0.01) {
    .Call(`_phutil_wasserstein_distance`, x, y, wasserstein_power, delta)
}

