# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname distances
#' @export
bottleneck_distance <- function(x, y, delta = 0.01) {
    .Call(`_phutil_bottleneck_distance`, x, y, delta)
}

#' @rdname distances
#' @export
wasserstein_distance <- function(x, y, delta = 0.01, wasserstein_power = 1.0) {
    .Call(`_phutil_wasserstein_distance`, x, y, delta, wasserstein_power)
}

