# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bottleneckDistExact <- function(x, y, decPrecision, verbose = FALSE) {
    .Call(`_phutil_bottleneckDistExact`, x, y, decPrecision, verbose)
}

bottleneckDistApprox <- function(x, y, delta, verbose = FALSE) {
    .Call(`_phutil_bottleneckDistApprox`, x, y, delta, verbose)
}

wassersteinDist <- function(x, y, wasserstein_power = 1.0, delta = 0.01) {
    .Call(`_phutil_wassersteinDist`, x, y, wasserstein_power, delta)
}

